services:
  db:
    image: postgres:15-alpine
    container_name: taskflow-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-taskflow}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-taskflow}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: taskflow-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET:-prod-change-me}
      POSTGRES_DSN: ${POSTGRES_DSN:-host=db user=postgres password=postgres dbname=taskflow port=5432 sslmode=disable TimeZone=UTC}
    ports: ["8080:8080"]
    restart: unless-stopped

volumes:
  pgdata:
